'use client';
import { useEffect, useState } from 'react';
import { Download, RefreshCw } from 'lucide-react';
import { exportToExcel } from '@/app/lib/excel-export';
import EmptyState from '../_components/EmptyState';
import ListPages from '../_components/ListPages';
const day=(offset=0)=>new Date(Date.now()+3*3600000-offset*86400000).toISOString().slice(0,10);
type Row={id:string;date:string;kind:string;party:string;reference:string;amount:number;direction:string;method:string};
type Data={rows:Row[];total:number;received:number;paid:number;matched:number;includesSuppliers:boolean;includesReps:boolean};
export default function FinancialActivity(){
 const [from,setFrom]=useState(day(29)),[to,setTo]=useState(day()),[direction,setDirection]=useState('ALL'),[search,setSearch]=useState(''),[page,setPage]=useState(1),[version,setVersion]=useState(0);
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');const timer=setTimeout(async()=>{try{const res=await fetch('/api/warehouse-portal/accounts/activity?'+new URLSearchParams({from,to,direction,search,page:String(page)}),{signal:controller.signal});const d=await res.json();if(!res.ok)throw Error(d.error);if(!controller.signal.aborted)setData(d);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'تعذر الاتصال');}finally{if(!controller.signal.aborted)setLoading(false);}},200);return()=>{clearTimeout(timer);controller.abort();};},[from,to,direction,search,page,version]);
 const input='rounded-lg border bg-background px-3 py-2 text-sm';
 const methods:Record<string,string>={CASH:'نقدي',BANK_TRANSFER:'تحويل مصرفي',TRANSFER:'تحويل',CARD:'بطاقة',OTHER:'أخرى'};
 return <section className="space-y-4 rounded-lg border bg-card p-4"><div className="flex justify-between gap-3"><div><h3 className="font-bold">سجل القبض والصرف والمطابقة</h3><p className="mt-1 text-sm text-muted-foreground">الحركات المسجلة من المصادر المصرّح بها؛ صافي الحركة ليس رصيد الصندوق ولا الربح.</p></div><button aria-label="تحديث سجل الحركة" onClick={()=>setVersion(v=>v+1)} className={input}><RefreshCw className="h-4 w-4"/></button></div>
  <div className="flex flex-wrap items-end gap-2"><label className="text-xs">من<input className={'mt-1 block '+input} aria-label="بداية سجل الحركة" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></label><label className="text-xs">إلى<input className={'mt-1 block '+input} aria-label="نهاية سجل الحركة" type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/></label><select aria-label="نوع الحركة" className={input} value={direction} onChange={e=>{setDirection(e.target.value);setPage(1);}}><option value="ALL">جميع الحركات</option><option value="IN">قبض</option><option value="OUT">صرف</option><option value="NEUTRAL">مطابقة فقط</option></select><input aria-label="بحث سجل الحركة" className={'min-w-40 flex-1 '+input} placeholder="الجهة أو المرجع" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div>
  <ListPages page={page} total={data?.total??0} loading={loading} error={error} setPage={setPage}/>
  {!loading&&!error&&data&&<><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['المقبوضات',data.received],['المدفوعات',data.paid],['صافي الحركة',data.received-data.paid],['مطابقات غير نقدية',data.matched]].map(([title,value])=><div key={title} className="rounded-lg border bg-muted/20 p-3"><div className="text-xs text-muted-foreground">{title}</div><div className="mt-2 font-bold tabular-nums">{Number(value).toLocaleString('ar-IQ-u-nu-latn')} د.ع</div></div>)}</div><p className="text-xs text-muted-foreground">الأرقام تخص كل النتائج المطابقة للفلاتر، وليست الصفحة فقط. {!data.includesSuppliers&&'مدفوعات الموردين غير مشمولة بصلاحيتك. '}{!data.includesReps&&'تحصيلات المندوبين غير مشمولة بصلاحيتك.'}</p>
  {data.rows.length?<><button className="inline-flex items-center gap-2 text-sm text-primary" onClick={()=>exportToExcel(data.rows.map(r=>({...r,method:methods[r.method]??r.method,direction:r.direction==='IN'?'قبض':r.direction==='OUT'?'صرف':'مطابقة'})),[{header:'التاريخ',key:'date',width:26},{header:'النوع',key:'kind',width:20},{header:'الجهة',key:'party',width:24},{header:'المرجع',key:'reference',width:28},{header:'الاتجاه',key:'direction',width:15},{header:'الطريقة',key:'method',width:20},{header:'المبلغ (د.ع)',key:'amount',width:18}], 'سجل_الحركة_صفحة_'+page,'الحركة')}><Download className="h-4 w-4"/>تصدير الصفحة</button><div className="overflow-auto"><table className="w-full text-sm"><thead className="bg-muted/40 text-right"><tr>{['التاريخ','الحركة','الجهة والمرجع','الطريقة','المبلغ (د.ع)'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.kind+r.id} className="border-t"><td className="whitespace-nowrap p-3">{new Date(r.date).toLocaleString('ar-IQ-u-nu-latn',{timeZone:'Asia/Baghdad'})}</td><td className="whitespace-nowrap p-3">{r.kind}</td><td className="p-3">{r.party}<div className="max-w-64 break-all text-xs text-muted-foreground">{r.reference}</div></td><td className="p-3">{methods[r.method]??r.method}</td><td className={'p-3 font-bold tabular-nums '+(r.direction==='OUT'?'text-destructive':r.direction==='IN'?'text-success':'text-muted-foreground')}>{r.amount.toLocaleString('ar-IQ-u-nu-latn')}</td></tr>)}</tbody></table></div></>:<EmptyState title="لا توجد حركات مطابقة" description="غيّر الفترة أو البحث للاطلاع على السجلات المتاحة."/>}</>}
 </section>;
}
