"use client";
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {MODE_LABELS, type WarehouseOperatingMode} from '@/app/lib/warehouse-operating-mode';
export default function OperatingMode({initialMode,canChange}:{initialMode:WarehouseOperatingMode;canChange:boolean}) {
 const [mode,setMode]=useState(initialMode),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const router=useRouter();
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/warehouse-portal/operating-mode',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,confirmed})});const d=await r.json();if(!r.ok)throw Error(d.error);setConfirmed(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:'تعذر الحفظ')}finally{setBusy(false)}}
 return <section className="rounded-lg border bg-card p-5 space-y-4"><h2 className="font-bold">طريقة تشغيل المذخر</h2><p className="text-sm text-muted-foreground">الوضع الحالي: {MODE_LABELS[initialMode]}. اختيار الوضع للمالك؛ صلاحيات الموظفين تبقى مطبقة في الحالتين.</p><div className="grid gap-3 md:grid-cols-2">{(['ORDER_PORTAL','FULL'] as const).map(v=><label key={v} className={`rounded-lg border p-4 cursor-pointer ${mode===v?'border-primary bg-primary/5':''}`}><input type="radio" name="operatingMode" disabled={!canChange||busy} checked={mode===v} onChange={()=>{setMode(v);setConfirmed(false)}}/> <strong>{MODE_LABELS[v]}</strong><p className="mt-2 text-sm leading-6 text-muted-foreground">{v==='ORDER_PORTAL'?'استقبل وسعّر وجهّز الشحنات دون إدخال كل مخزونك. أدخل دفعات الشحنة والصلاحية والكميات الفعلية. الأرصدة والفحص المخزني تُدار في نظامك الآخر.':'أدخل أرصدتك الافتتاحية ودفعاتها وتكلفتها الحقيقية. لا يسمح بالشحن قبل وجود مخزون كافٍ. تُخصم الشحنات وتُعاد المرتجعات بعد الفحص إلى الدفعات الأصلية.'}</p></label>)}</div><p className="text-xs leading-6 text-muted-foreground">تغيير الوضع لا يحوّل الشحنات القديمة إلى مخزون. المذخر الذي سجل دفعات أو مشتريات يبقى في الإدارة الكاملة لحماية سجله. تفعيل الإدارة الكاملة لا ينشئ أرصدة تلقائيًا؛ أدخلها من المخزون قبل أول شحن.</p>{canChange&&mode!==initialMode&&<><label className="flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>أفهم طريقة التشغيل، وسأسجل الأرصدة الفعلية قبل الشحن عند تفعيل الإدارة الكاملة.</label><button disabled={busy||!confirmed} onClick={save} className="rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50">{busy?'جارٍ الحفظ…':'حفظ طريقة التشغيل'}</button></>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}</section>;
}
