"use client";
import {useState} from 'react';
import {createPortal} from 'react-dom';
import {validatePortalShipment, type ShipmentLot} from '@/app/lib/warehouse-operating-mode';
export default function PortalShipment({order,onClose,onSave}:{order:any;onClose:()=>void;onSave:(lots:ShipmentLot[])=>Promise<boolean>}){
 const items=order.items.filter((i:any)=>i.status!=='OUT_OF_STOCK');
 const expected=items.map((i:any)=>({drugId:i.drugId,quantity:(i.status==='PARTIAL'?i.quotedQuantity??0:i.quantity)+(i.bonusQuantity||0)}));
 const [lots,setLots]=useState<ShipmentLot[]>(expected.map((i:any)=>({...i,batchNumber:'',expiryDate:''}))),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const patch=(index:number,value:Partial<ShipmentLot>)=>setLots(old=>old.map((r,i)=>i===index?{...r,...value}:r));
 async function save(){if(busy)return;setBusy(true);setError('');try{const validated=validatePortalShipment(lots,expected);if(await onSave(validated))onClose();else setError('لم تُسجل الشحنة؛ راجع رسالة الخطأ وأعد المحاولة.');}catch(e){setError(e instanceof Error?e.message:'راجع البيانات')}finally{setBusy(false)}}
 return createPortal(<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" dir="rtl"><section role="dialog" aria-modal="true" aria-labelledby="portal-shipment-title" className="w-full max-w-3xl max-h-[90vh] overflow-y-auto rounded-lg border bg-card p-5 space-y-4"><h2 id="portal-shipment-title" className="font-bold">تجهيز الشحنة — {order.orderNumber}</h2><p className="text-sm text-muted-foreground">أدخل البيانات الموجودة على العبوات. الكمية بالباكيت وتشمل البونص؛ هذه بيانات شحنة للصيدلية ولا تُنشئ مخزونًا للمذخر.</p>{items.map((item:any)=><div className="rounded-lg border p-3 space-y-2" key={item.id}><strong>{item.drug.tradeName}</strong><p className="text-xs text-muted-foreground">المطلوب مع البونص: {expected.find((i:any)=>i.drugId===item.drugId)?.quantity} باكيت</p>{lots.map((lot,index)=>lot.drugId!==item.drugId?null:<div key={index} className="grid grid-cols-1 sm:grid-cols-[1fr_1fr_100px_auto] gap-2"><label className="text-xs">رقم الدفعة<input disabled={busy} className="mt-1 w-full rounded-lg border bg-background p-2" value={lot.batchNumber} onChange={e=>patch(index,{batchNumber:e.target.value})}/></label><label className="text-xs">الصلاحية<input disabled={busy} type="date" className="mt-1 w-full rounded-lg border bg-background p-2" value={lot.expiryDate} onChange={e=>patch(index,{expiryDate:e.target.value})}/></label><label className="text-xs">الكمية<input disabled={busy} type="number" min="1" step="1" className="mt-1 w-full rounded-lg border bg-background p-2" value={lot.quantity} onChange={e=>patch(index,{quantity:Number(e.target.value)})}/></label><button disabled={busy} aria-label="حذف الدفعة" onClick={()=>setLots(old=>old.filter((_,i)=>i!==index))} className="text-destructive">حذف</button></div>)}<button disabled={busy} onClick={()=>setLots(old=>[...old,{drugId:item.drugId,quantity:0,batchNumber:'',expiryDate:''}])} className="text-xs text-primary">+ إضافة دفعة أخرى للدواء</button></div>)}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex gap-2"><button disabled={busy} onClick={save} className="rounded-lg bg-primary px-4 py-2 text-primary-foreground disabled:opacity-50">{busy?'جارٍ تسجيل الشحنة…':'تأكيد البيانات والشحن'}</button><button disabled={busy} onClick={onClose} className="rounded-lg border px-4 py-2">إلغاء</button></div></section></div>,document.body);
}
